version: '3'
services:
  social-backend:
    image: social-backend
    env_file:
     - ./social-backend/.env
    container_name: social-backend
    build:
      context: .
      dockerfile: ./dockerfiles/social-backend/dockerfile
    ports:
      - 5000:5000
    volumes: 
      - ./social-backend/app/:/code/social-backend
      - ./scripts/healthcheck/social-backend-healthcheck.sh:/code/scripts/social-backend-healthcheck.sh
      - /code/social-backend/node_modules/
    depends_on:
      - social-db
  social-db:
    image: social-db
    container_name: social-db
    build:
      context: .
      dockerfile: ./dockerfiles/social-db/dockerfile
    ports:
      - "27017:27017"
    volumes:
    - ./social-data/:/data/db/
  social-frontend:
    image: social-frontend
    env_file:
     - ./social-frontend/.env
    container_name: social-frontend
    build:
      context: .
      dockerfile: ./dockerfiles/social-frontend/dockerfile
    ports:
      - 3000:3000
    volumes:
    - ./social-frontend/:/code/
    - /code/node_modules/
    depends_on:
      - social-backend
volumes:
  social-frontend:
  social-backend:
  social-data: