version: '2.1'
services:
  # social-frontend:
  #   image: social-frontend
  #   container_name: social-frontend
  #   build:
  #     context: .
  #     dockerfile: ./dockerfiles/social-frontend/dockerfile
  #   ports:
  #     -3000:3000
  #   volumes:


  social-backend:
    image: social-backend
    container_name: social-backend
    build:
      context: .
      dockerfile: ./dockerfiles/social-backend/dockerfile
    ports:
      - 5000:5000
    volumes: 
      - ./social-backend/app/:/code/social-backend
      - /code/social-backend/node_modules/
    depends_on:
      mongo:
        condition: service_healthy
    command: npm run server
  mongo:
    image: mongo
    container_name: social-db    
    ports:
      - "27017:27017"
    volumes:
    - ./social-data/:/data/db/
    - ./scripts/mongo/mongo_healthcheck.sh:/code/scripts/mongo_healthcheck.sh
    healthcheck:
      test: /code/scripts/mongo_healthcheck.sh
volumes:
  social-backend:
  social-data: