version: '2.1'
services:
  social-backend:
    image: social-backend
    env_file:
     - ./social-backend/.env
    container_name: social-backend
    build:
      context: .
      dockerfile: ./dockerfiles/social-backend/dockerfile
    ports:
      - 5000:5000
    volumes: 
      - ./social-backend/app/:/code/social-backend
      - ./scripts/healthcheck/social-backend-healthcheck.sh:/code/scripts/social-backend-healthcheck.sh
      - /code/social-backend/node_modules/
    depends_on:
      social-db:
        condition: service_healthy
    healthcheck:
      test: /code/scripts/social-backend-healthcheck.sh
  social-db:
    image: mongo
    container_name: social-db
    ports:
      - "27017:27017"
    volumes:
    - ./social-data/:/data/db/
    - ./scripts/healthcheck/mongo_healthcheck.sh:/code/scripts/mongo_healthcheck.sh
    healthcheck:
      test: /code/scripts/mongo_healthcheck.sh
  social-frontend:
    image: social-frontend
    env_file:
     - ./social-frontend/.env
    container_name: social-frontend
    build:
      context: .
      dockerfile: ./dockerfiles/social-frontend/dockerfile
    ports:
      - 3000:3000
    volumes:
    - ./social-frontend/:/code/
    - /code/node_modules/
    depends_on:
      social-backend:
        condition: service_healthy
    # Use environment label only when we need to get env variables from the host shell, maybe secrets
    # environment: 
    #   - PORT=${PORT}
    #   - ADDRESS=${ADDRESS}
volumes:
  social-frontend:
  social-backend:
  social-data: