# alpine does not include curl or apt-get tools needed to do healthchecks of containers
# FROM node:11.6.0-alpine
FROM node:11.10.1-stretch
# the following line is to install jq in order to process the results from the curl request to the test endpoint
RUN apt-get update && apt-get install jq -y
WORKDIR /code/social-backend
ADD ./social-backend/app/ /code/social-backend
ADD ./scripts/setup/setup_backend.sh /code/scripts/setup_backend.sh
ADD ./scripts/healthcheck/social-backend-healthcheck.sh /code/scripts/social-backend-healthcheck.sh
RUN chmod +x /code/scripts/social-backend-healthcheck.sh
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD sh /code/scripts/social-backend-healthcheck.sh
# RUN command executes on the container not locally on the host
RUN /code/scripts/setup_backend.sh
RUN chmod +x /code/scripts/setup_backend.sh
ENTRYPOINT [ "sh", "./setup_backend"]