# alpine does not include curl or apt-get tools needed to do healthchecks of containers
# FROM node:11.6.0-alpine
FROM node:11.10.1-stretch
# the following line is to install jq in order to process the results from the curl request to the test endpoint
RUN apt-get update && apt-get install jq -y
WORKDIR /code/social-backend
ADD ./social-backend/app/ /code/social-backend
ADD ./scripts/project/setup_backend.sh /code/scripts/setup_backend.sh
# RUN command executes on the container not locally on the host
RUN /code/scripts/setup_backend.sh
ENTRYPOINT [ "npm", "run", "server" ]