FROM node:11.6.0-alpine
WORKDIR /code/
ADD ./social-frontend/ /code/
ADD ./scripts/project/setup_frontend.sh /code/scripts/setup_frontend.sh
# RUN command executes on the container not locally on the host
RUN /code/scripts/setup_frontend.sh
ENTRYPOINT ["npm", "run", "start"]
