FROM node:11.10.1-stretch
WORKDIR /code/
ADD ./social-frontend/ /code/
ADD ./scripts/setup/setup_frontend.sh /code/scripts/setup_frontend.sh
# RUN command executes on the container not locally on the host
RUN /code/scripts/setup_frontend.sh
ENTRYPOINT ["yarn", "run", "start"]
