version: '2.1'
services:
  social-backend:
    image: social-backend
    container_name: social-backend
    build:
      context: .
      dockerfile: ./dockerfiles/social-backend/dockerfile
    ports:
      - "5000:5000"
    volumes: 
      - ./app/:/code/
      - /code/node_modules/
    depends_on:
      mongo:
        condition: service_healthy
    command: npm run server
  mongo:
    image: mongo
    container_name: social-db    
    ports:
      - "27017:27017"
    volumes:
    - ../social-data/:/data/db/
    - ./app/scripts/mongo/mongo_healthcheck.sh:/scripts/mongo_healthcheck.sh
    healthcheck:
      test: /scripts/mongo_healthcheck.sh
volumes:
  app: