version: '3'
services:
  social-backend:
    image: social-backend
    container_name: social-backend
    build:
      context: .
      dockerfile: ./dockerfiles/social-backend/Dockerfile
    ports:
      - "5000:5000"
    volumes: 
      - ./app/:/code/
      - /code/node_modules/
    depends_on:
      - mongo
  mongo:
    container_name: social-db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
    - ../social-data/:/data/db/
volumes:
    app: