version: '3'
services:
  social-backend:
    image: social-backend
    container_name: social-backend
    build:
      context: .
      dockerfile: ./dockerfiles/social-backend/Dockerfile
    ports:
      - "5000:5000"
    volumes: 
      - ./app/:/code/
      - /code/node_modules/
    depends_on:
      - mongo
    command: npm run server
  mongo:
    image: mongo:latest
    container_name: social-db    
    ports:
      - "27017:27017"
    volumes:
    - ../social-data/:/data/db/
    - ./app/scripts/:/scripts
    healthcheck                                                               :
      test: ./scripts/mongo_healthcheck.sh
volumes:
  app: